version: '3.3'

volumes:
  postgres_data:
  staticfiles:

services:
  db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_USER=django_user
      - POSTGRES_DB=django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: goglogige/foodgram:latest
    restart: always
    volumes:
      - staticfiles:/code/static
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    image: nginx:1.19.6
    restart: always
    volumes:
      - staticfiles:/static
      - ./host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
