version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:12.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_USER=django_user
      - POSTGRES_DB=django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    image: goglogige/foodgram:latest
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6
    restart: always
    ports:
      - 80:80
    volumes:
      - ./host.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - app
