# Generated by Django 3.0.5 on 2021-10-10 09:35

import django.core.validators
from django.db import migrations
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210926_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=recipes.models.PositiveIntegerWithoutZeroField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Не менее 1 минуты')], verbose_name='время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=recipes.models.PositiveDecimalWithoutZeroField(decimal_places=1, max_digits=7, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Введите не менее 1 единицы ингредиента!')], verbose_name='количество'),
        ),
    ]
